### ISSUE TITLE
Not an issue but read the thread

### ISSUE THREAD

**Issue by blacbrue** [Growtopian-Bot/growtopia-api#2]
The console.log thingy works but how do I put the output to html?

**Comment by AykutSarac** [comment]
You should have basic knowledge in order to do that. 

This video may help you https://youtu.be/gwTkd52Dm48

**Comment by blacbrue** [comment]
> You should have basic knowledge in order to do that.
> 
> This video may help you https://youtu.be/gwTkd52Dm48

Okay thanks! I will take a look at it!
